### PR TITLE
[WIP] Add percentage efficiency for water heating

### PR DESCRIPTION
**Pull request by buckley-w-david**
This PR adds capability to understand when efficiency values are in the form as a percentage.

It also cleans up some of the exception handling

### CODE REVIEW

**Comment by buckley-w-david** [comment]
Before this can be merged, I think we'll need an addition (in this branch) from either @pcraig3 or @sleepycat that changes the API side.

**Comment by sleepycat** [comment]
@buckley-w-david I'll tackle that today.

**Comment by JasonMWhite** [comment]
Just checking - did you get a 👍  on this PR before merging? Also note that the title was never changed from `WIP` which is a signal to _not_ give this PR a thorough review.

**Comment by buckley-w-david** [comment]
Good point, completely missed that since I was going back and forth with Mike so much it just slipped my mind that anyone from the etl crew had yet to take a look at it.

**Pull request merged**
